name: Integration Tests Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
    - name: Install dependencies
      run: |
        npm ci && npx tsc --version
    - name: Run Integration Tests
      run: |
        npm run headless-bin -- ./fixtures/simple.xsml
        npm run headless-bin -- ./fixtures/spatial-element.xsml
        npm run headless-bin -- ./fixtures/esm/script-with-src.xsml
        npm run headless-bin -- ./fixtures/esm/script-inline.xsml
        npm run headless-bin -- ./fixtures/css/spatial-basic.xsml
        npm run headless-bin -- ./fixtures/css/spatial-material-bumpmap.xsml
        npm run headless-bin -- ./fixtures/css/spatial-material-canvasapi.xsml
