name: Integration Tests Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.74.0
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        export PATH=$HOME/.cargo/bin:$HOME/.wasm-pack/bin:$PATH
    - name: Build bindings
      run: |
        wasm-pack build bindings/taffy --target web
        node ./bindings/tools/generate-wasm-js.cjs
    - name: Install Node.js dependencies
      run: |
        npm ci && npx tsc --version
    - name: Run Integration Tests
      run: |
        npm run headless-bin -- ./fixtures/simple.xsml
        npm run headless-bin -- ./fixtures/spatial-element.xsml
        npm run headless-bin -- ./fixtures/esm/script-with-src.xsml
        npm run headless-bin -- ./fixtures/esm/script-inline.xsml
        npm run headless-bin -- ./fixtures/css/spatial-basic.xsml
        npm run headless-bin -- ./fixtures/css/spatial-material-bumpmap.xsml
