name: Integration Tests Build

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.74.0
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
    - name: Install Node.js dependencies
      run: |
        npm ci && npx tsc --version
    - name: Build bindings
      run: |
        npm run bindings
    - name: Run Integration Tests
      run: |
        npm run headless-bin -- ./fixtures/simple.xsml
        npm run headless-bin -- ./fixtures/spatial-element.xsml
        npm run headless-bin -- ./fixtures/spatial-polyhedra-element.xsml
        npm run headless-bin -- ./fixtures/esm/script-with-src.xsml
        npm run headless-bin -- ./fixtures/esm/script-inline.xsml
        npm run headless-bin -- ./fixtures/esm/http-imports.xsml
        npm run headless-bin -- ./fixtures/custom-loader/custom-resolve.xsml
        npm run headless-bin -- ./fixtures/custom-loader/custom-load.xsml
        npm run headless-bin -- ./fixtures/css/spatial-basic.xsml
        npm run headless-bin -- ./fixtures/css/spatial-material-bumpmap.xsml
        npm run headless-bin -- ./fixtures/dom/globals-in-script.xsml
