name: Release

on:
  workflow_run:
    workflows: [ "Build", "Integration Tests Build" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.74.0
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
        registry-url: 'https://registry.npmjs.org'
    - name: Install Node.js dependencies
      run: npm ci && npx tsc --version
    - name: Build bindings
      run: |
        npm run bindings
    - name: Build release
      run: |
        node ./version.cjs
        npm run build-release
        npm run build-types
    - name: Upload core release to artifact
      uses: actions/upload-artifact@v2
      with:
        name: jsardom-release
        path: './dist'
    - name: Publish core to npm
      run: |
        npm publish --tag daily --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish types to npm
      working-directory: ./types
      run: |
        npm publish --tag daily --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
